development:
  adapter: postgresql
  encoding: unicode
  database: voicey_development
  pool: 5
  username: melodyfs
  password: mfs16

test:
  adapter: postgresql
  encoding: unicode
  database: voicey_test
  pool: 5
  username: melodyfs
  password: mfs16


production:
  adapter: postgresql
  encoding: unicode
  database: voicey_production
  pool: 5
  username: melodyfs
  password: mfs16
